# Positional PID Control that takes the target position and executes an instruction to got to this position

In [1]:
import matplotlib.pyplot as plt
import numpy as np

**Forward Kinematics**

In [3]:
r = .01 #meter wheel radius
b = .02 #meter robot radius


In [4]:
w1 = 255 #  rad/s
w2 = 255 #  rad/s
w3 = 255 #  rad/s

v1 = w1 * r
v2 = w2 * r
v3 = w3 * r

alpha1 = 30 # degreer
alpha2 = 150 # degree
alpha3 = 270 # degree


In [5]:
v = np.array([[v1],
              [v2],
              [v3]])

k = np.array([[np.cos((alpha1+90) * (np.pi/180)),np.cos((alpha2+90) * (np.pi/180)),np.cos((alpha3+90) * (np.pi/180))],
             [np.sin((alpha1+90) * (np.pi/180)),np.sin((alpha2+90) * (np.pi/180)),np.sin((alpha3+90) * (np.pi/180))],
             [1/b,1/b,1/b]])

vl = k @ v
print(f"vl: \n{np.round(vl,2)}")

vl: 
[[ -0. ]
 [  0. ]
 [382.5]]


**Inverse Kinematics**

In [6]:
alpha1 = 30 # degree
alpha2 = 150 # degree
alpha3 = 270 # degree

vx = int(input("Enter Vx = ")) # m/s
vy = int(input("Enter Vy = ")) # m/s
w = int(input("Enter W = ")) # rad/s

vl = np.array([[vx],
              [vy],
              [w]])

k = np.array([[np.cos((alpha1+90) * (np.pi/180)),np.cos((alpha2+90) * (np.pi/180)),np.cos((alpha3+90) * (np.pi/180))],
             [np.sin((alpha1+90) * (np.pi/180)),np.sin((alpha2+90) * (np.pi/180)),np.sin((alpha3+90) * (np.pi/180))],
             [1/b,1/b,1/b]])


v = np.linalg.inv(k) @ vl # m/s
print(f"v: \n{np.round(v,2)}")



Enter Vx = 2
Enter Vy = 4
Enter W = 5
v: 
[[ 1.68]
 [-2.94]
 [ 1.37]]


In [7]:
angular_velo = v/r
print(f"angular_velo: \n{np.round(angular_velo,2)}") # rad/s

rpm = (angular_velo*60)/(2*np.pi)
print(f"rpm of each motor: \n{np.round(rpm,2)}") # rpm

theta = 0
rot = np.array([[np.cos(theta * (np.pi/180)),-np.sin(theta * (np.pi/180)),0],
             [np.sin(theta * (np.pi/180)),np.cos(theta * (np.pi/180)),0],
             [0,0,1]])

vg = rot @ vl
print(f"vg: \n{np.round(vg,2)}")


angular_velo: 
[[ 167.61]
 [-294.27]
 [ 136.67]]
rpm of each motor: 
[[ 1600.53]
 [-2810.1 ]
 [ 1305.07]]
vg: 
[[2.]
 [4.]
 [5.]]
